services:
  weewx:
    image: thrawn.home:5000/weewx:0.0.14
    container_name: weewx
    restart: unless-stopped
    volumes:
      - db:/home/weewx/archive
      - html:/home/weewx/public_html
    devices:
      - /dev/VantageUSB:/dev/ttyUSB0
  nginx:
    container_name: weewx-nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - weewx
    volumes:
      - html:/usr/share/nginx/html
  mosquitto:
    restart: unless-stopped
    container_name: weewx-mosquitto
    image: thrawn.home:5000/mosquitto:0.0.3
    volumes:
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log

volumes:
  db:
  html:
  mqtt-data:
  mqtt-log:

networks:
  default:
    external: true
    name: private
