services:
  weewx:
    container_name: weewx
    build:
      context: ./container/weewx
      secrets:
        - mqtt_password
    restart: unless-stopped
    volumes:
      - db:/home/weewx/archive
      - html:/home/weewx/public_html
    devices:
      - /dev/VantageUSB:/dev/ttyUSB0
  nginx:
    container_name: weewx-nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - weewx
    volumes:
      - html:/usr/share/nginx/html
  mosquitto:
    container_name: weewx-mosquitto
    build:
      context: ./container/mosquitto
      secrets:
        - mqtt_password
    restart: unless-stopped
    volumes:
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log

volumes:
  db:
  html:
  mqtt-data:
  mqtt-log:

networks:
  default:
    external: true
    name: private

secrets:
  mqtt_password:
    file: stack.env
